# Generated by Django 2.1.3 on 2018-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hello',
            field=models.CharField(default='', max_length=264),
        ),
    ]
