# Generated by Django 2.1.3 on 2018-12-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_question_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hello',
        ),
    ]
