# Generated by Django 2.1.3 on 2018-12-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_question_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillot',
            name='test',
        ),
    ]
