# Generated by Django 2.1.3 on 2018-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20181209_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264)),
                ('password', models.CharField(max_length=264)),
                ('profile_picture', models.ImageField(default='static/images/profile.jpg', upload_to='static/images/profile_pictures/')),
            ],
        ),
    ]
