# Generated by Django 2.1.3 on 2018-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maillots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='static/images/image.png', upload_to='static/images/')),
            ],
        ),
    ]
