# Generated by Django 2.1.3 on 2018-12-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='customer_name',
            new_name='username',
        ),
    ]
