# Generated by Django 2.1.3 on 2018-12-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_maillots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maillots',
            new_name='Maillot',
        ),
    ]
