# Generated by Django 2.1.3 on 2018-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20181211_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillot',
            name='image',
            field=models.ImageField(default='static/images/image.png', upload_to='static/images/images_maillots/'),
        ),
    ]
