# Generated by Django 2.1.3 on 2018-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_auto_20181215_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/image.jpeg', upload_to='static/images/'),
        ),
    ]
