# Generated by Django 2.1.3 on 2018-12-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_auto_20181215_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='shoes',
            field=models.ImageField(default='static/images/image.jpeg', upload_to='static/images/shoes/'),
        ),
    ]
